/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap': typeof SitemapRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap': typeof SitemapRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap': typeof SitemapRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap'
    | '/sobre'
    | '/termos-de-uso'
    | '/categoria/$slug'
    | '/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap'
    | '/sobre'
    | '/termos-de-uso'
    | '/categoria/$slug'
    | '/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap'
    | '/sobre'
    | '/termos-de-uso'
    | '/categoria/$slug'
    | '/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapRoute: typeof SitemapRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapRoute: SitemapRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
